# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    command: >
      sh -c "echo 'Running migrations...' &&
      alembic upgrade head &&
      echo 'Starting app...' &&
      uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: